apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-chart-template.name" . }}
  labels:
    {{- include "service-chart-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service-chart-template.name" . }}
  template:
    metadata:
      labels:
        {{- include "service-chart-template.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          {{- if .Values.secrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.syncK8sSecretName }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          {{- if .Values.secrets.enabled }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          {{- end }}
      {{- if .Values.secrets.enabled }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "service-chart-template.name" . }}-kv
      {{- end }}
