{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "service-chart-template.name" . }}-kv
  labels:
    {{- include "service-chart-template.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secrets.managedIdentityClientId | quote }}
    keyvaultName: {{ .Values.secrets.keyvaultName | quote }}
    tenantId: {{ .Values.secrets.tenantId | quote }}
    {{- with .Values.secrets.cloudName }}
    cloudName: {{ . | quote }}
    {{- end }}
    {{- with .Values.secrets.cloudEnvFileName }}
    cloudEnvFileName: {{ . | quote }}
    {{- end }}
    objects: |
      array:
        {{- range .Values.secrets.objects }}
        - |
          objectName: {{ .name }}
          objectType: secret
        {{- end }}
  secretObjects:
    - secretName: {{ .Values.secrets.syncK8sSecretName }}
      type: Opaque
      data:
        {{- range .Values.secrets.objects }}
        - objectName: {{ .name }}
          key: {{ .env }}
        {{- end }}
{{- end }}
