apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart-template.name" . }}
  labels:
    {{- include "service-chart-template.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "service-chart-template.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
